### ISSUE TITLE
OpenAI & Youtube Token in Notebook

### ISSUE THREAD

**Issue by rowillia** [ClerkieAI/berri_ai#1]
FYI you're publicly sharing your Youtube and OpenAI tokens on https://colab.research.google.com/drive/1Do4Utp4crMSpPngDlZOXx30HFmKhtxIF?usp=sharing

**Comment by krrishdholakia** [comment]
thanks for the heads up - we did that intentionally to  make it easier for people to try it out, but looks like we got rate limited 😄
